apiVersion: v1
kind: Service
metadata:
  name: darwin-agentic-cloud
  namespace: poc-darwin-agentic-cloud
  labels:
    app: darwin-agentic-cloud
    autopoc.io/project: darwin-agentic-cloud
spec:
  type: ClusterIP
  selector:
    app: darwin-agentic-cloud
  ports:
    - port: 8787
      targetPort: 8787
